get:
  summary: Returns all products
  parameters:
    - in: query
      name: limit
      schema:
        type: integer
        maximum: 1000
        default: 1000
      required: false
      description: The number of items to return
    - in: query
      name: page
      schema:
        type: integer
      required: false
      description: Page with the amount of returned item
    - in: query
      name: query
      schema:
        type: string
      required: false
      description: searches for product based on query parameter. Searches only in productNumber
    - in: query
      name: partnerBrand
      schema:
        type: integer
      required: false
      description: Id of brand company. Allows to fetch products as service partner for brand
  description: ""
  tags:
    - Products
  responses:
    '200':
      description: Ok
      content:
        application/json:
          schema:
            type: object
            properties:
              count:
                type: integer
              products:
                properties:
                  productId:
                    type: integer
                  companyId:
                    type: integer
                  productNumber:
                    type: string
                  productGroup:
                    type: string
                  productDescription:
                    type: string
                  remark:
                    type: string
          example:
            {
              "result": {
                "count": 2,
                "products": [
                  {
                    "productId": 10000350,
                    "companyId": 7378787652899,
                    "productNumber": "18/15",
                    "productGroup": "afzuigkap",
                    "productDescription": "Twist wandschouw",
                    "remark": "Can't sell directly",

                  },
                  {
                    "productId": 10000351,
                    "companyId": 7378787652899,
                    "productNumber": "16/15",
                    "productGroup": "afzuigkap",
                    "productDescription": "Salsa wandschouw",
                    "remark": "",
                  }
                ]
              }
            }
post:
  summary: Creates a new product with the supplied data
  parameters:
    - in: query
      name: partnerBrand
      schema:
        type: integer
      required: false
      description: Id of brand company. Allows to create product as service partner for brand
  description: ""
  tags:
    - Products
  requestBody:
    content:
      application/json:
        schema:
          type: object
          properties:
            productNumber:
              type: string
            productDescription:
              type: string
            productDescriptionExtra:
              type: string
            productGroup:
              type: string
              required: true
            productNumberExtra:
              type: string
            productManufacturer:
              type: string
            productManufacturerNumber:
              type: string
            productBrand:
              type: string
            eanCode:
              type: string
            remark:
              type: string
          required:
            - productNumber
            - productDescription
            - productGroup
        example:
          { "productNumber": "1010/5","productDescription": "wandschouw","productGroup": "afzuigkap" }
  responses:
    '201':
      description: Created
      content:
        application/json:
          schema:
            type: object
            properties:
              id:
                type: string
              status:
                type: integer
          example:
            {
              "status": 201,
              "id": "50001",
            }
    '400':
      description: Bad Request
    '422':
      description: Unprocessable Entity