get:
  summary: Returns product group information by id
  description: ""
  tags:
    - ProductGroups
  responses:
    '200':
      description: Ok
      content:
        application/json:
          schema:
            type: object
            properties:
              id:
                type: integer
              group:
                type: string
              estimatedRepairTime:
                type: integer
          example:
            {
              "result": {
                "id": 10000350,
                "group": "Oven",
                "estimatedRepairTime": "3600",
              }
            }